☁️ Automation

diff --git a/.config/taskfiles/fix/Taskfile.yml b/.config/taskfiles/fix/Taskfile.yml
--- a/.config/taskfiles/fix/Taskfile.yml
+++ b/.config/taskfiles/fix/Taskfile.yml
@@ -23,9 +23,10 @@ tasks:
     deps:
       - :install:modules:local
       - :install:npm:eslint
-    desc: Fix JavaScript/TypeScript errors automatically
+      - :install:software:expect
+    desc: Fix ESLint errors automatically
     summary: |
-      # Fix JavaScript/TypeScript errors automatically with `eslint`
+      # Fix Errors with ESLint Automatically
 
       This task is an [`eslint`](https://eslint.org/) task. It will attempt to automatically fix
       `eslint` issues. It will report any issues it was unable to fix. The configuration found in
@@ -34,15 +35,82 @@ tasks:
       **Example using `eslint` to fix a single JS/TS file:**
       `task fix:js -- single.ts`
 
-      **Example fixing all JS/TS files in a project:**
+      **Example fixing all files in a project:**
       `task fix:js`
     log:
       error: ESLint found some issues that need to be fixed manually
       start: Auto-fixing with ESLint
       success: ESLint fixing appears to have corrected all the issues {{if .CLI_ARGS}}in `{{.CLI_ARGS}}`{{else}}in the project{{end}}
     cmds:
-      - '{{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format pretty --cache --cache-location .cache/eslintcache
-        --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - 'unbuffer {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache
+        --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee eslint.log'
+      - |
+        if [ '{{.ESLINT_FIX_RECURSIVE}}' == 'true' ]; then
+          COUNT=0
+          while [ $COUNT -le 5 ]; do
+            COUNT=$((COUNT + 1))
+            if grep 'potentially fixable with the `--fix` option' < eslint.log > /dev/null; then
+              COUNT="$COUNT"
+              unbuffer {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache \
+              --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee eslint.log
+            else
+              echo '' > eslint.log
+            fi
+          done
+        fi
+      - rm eslint.log
+
+  eslint:staged:
+    deps:
+      - :install:modules:local
+      - :install:npm:eslint
+    desc: Auto-fix only modified files with ESLint
+    env:
+      ESLINT_STAGED_ONLY: on
+    log:
+      error: Failed to auto-fix modified files with ESLint
+      start: Auto-fixing modified files with ESLint
+      success: Successfully auto-fixed modified files with ESLint
+    cmds:
+      - >
+        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
+        --cache-location .cache/eslintcache --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+
+  go:
+    desc: Fix Go with all available Go fixers
+    summary: |
+      # Auto-Fix Go Files
+
+      This task will attempt to auto-fix Go files with the following auto-fixers:
+
+      * [go]()
+
+      If you would like to skip auto-fixing on the whole project and instead auto-fix an
+      individual file, then you can do so by passing the file path as a CLI
+      parameter like so:
+
+      **Example auto-fixing an individual file:**
+      `task fix:go -- path/filename.go`
+    cmds:
+      - task: go:fmt
+
+  go:fmt:
+    deps:
+      - :install:software:go
+    summary: |
+      # Auto-Fix Go Files with `gofmt`
+
+      Running this task will auto-format the Go code in the project with `gofmt`.
+      In addition to writing the files (via the `-w` flag), it also attempts to
+      simplify the files (via the `-s` flag).
+
+      By default, this task will format the entire project. However, you can target
+      specific files by passing the path of the `.go` file as a CLI argument.
+
+      **Example formatting specific file:**
+      `task fix:go:fmt -- path/to/file.go`
+    cmds:
+      - gofmt -s -w {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   js:
     cmds:
@@ -52,9 +120,9 @@ tasks:
     deps:
       - :install:modules:local
       - :install:npm:eslint
-    desc: Alphabetically sort JSON
+    desc: Format and sort JSON
     summary: |
-      # Automatically alphabetize JSON
+      # Automatically Alphabetize and Format JSON
 
       This task will format and organize JSON files based on the configuration stored in
       `.eslintrc.cjs`.
@@ -72,10 +140,41 @@ tasks:
       - '{{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --cache --cache-location .cache/eslintcache --fix
         --format pretty --ext .json {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
 
+  markdown:
+    deps:
+      - :install:npm:markdown-table-formatter
+    desc: Auto-fixes markdown files
+    summary: |
+      # Auto-Fix Markdown Files
+
+      This task performs various tasks that cleanup markdown files. It currently:
+
+      1. Runs `markdown-table-formatter` which fixes up markdown tables
+
+      You can either pass a file as a CLI argument or run it without a CLI argument to
+      auto-fix all the markdown files in the project that are not ignored by .gitignore.
+
+      **Example running against whole project:**
+      `task fix:markdown`
+
+      **Example running on single file:**
+      `task fix:markdown -- README.md`
+    log:
+      error: Error encountered while auto-fixing markdown file(s)
+      start: Auto-fixing markdown file(s)
+      success: Successfully finished auto-fixing markdown file(s)
+    cmds:
+      - >
+        {{if .CLI_ARGS}}
+        markdown-table-formatter {{.CLI_ARGS}}
+        {{else}}
+        find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.md' \)
+        -print0 | xargs -0 -r -n1 markdown-table-formatter
+        {{end}}
+
   misc:
     deps:
       - :install:python:requirements
-    desc: Perform miscellaneous fixes such as removing BOM and ensuring LF line endings
     summary: |
       # Miscellaneous fixes
 
@@ -104,15 +203,15 @@ tasks:
           misc '{{.CLI_ARGS}}'
         {{else}}
           while read PATHH; do
-            misc "$PATHH" &
+            misc "$PATHH"
           done < <(find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f)
-          wait
         {{end}}
 
   packer:
     deps:
       - :install:software:packer
     desc: Automatically fix and format Packer templates
+    hide: '{{ne .REPOSITORY_TYPE "packer"}}'
     summary: |
       # Automatically fix and format Packer templates
 
@@ -143,10 +242,27 @@ tasks:
           packerFix '{{.CLI_ARGS}}'
         {{else}}
           for TEMPLATE in *template.json; do
-            packerFix "$TEMPLATE" &
+            packerFix "$TEMPLATE"
           done
-          wait
         {{end}}
+
+  php:
+    desc: Fix PHP with all available PHP auto-fixers
+    summary: |
+      # Auto-Fix PHP Files
+
+      This task will attempt to auto-fix PHP files with the following auto-fixers:
+
+      * [go]()
+
+      If you would like to skip auto-fixing on the whole project and instead auto-fix an
+      individual file, then you can do so by passing the file path as a CLI
+      parameter like so:
+
+      **Example auto-fixing an individual file:**
+      `task fix:php -- path/filename.php`
+    cmds:
+      - task: :donothing
 
   prettier:
     deps:
@@ -154,7 +270,7 @@ tasks:
       - :install:npm:prettier
     desc: Automatically format most files using Prettier
     summary: |
-      # Automatically format most files using Prettier
+      # Automatically Format Files Using Prettier
 
       This task will run Prettier on the project. Prettier will automatically fix formatting
       mistakes like inconsistent indent lengths, trailing spaces, and more. It will use the
@@ -173,14 +289,20 @@ tasks:
     log:
       start: Running Prettier on {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}project{{end}}
     cmds:
-      - '{{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - |
+        {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
+        if [ -n "$EXIT_CODE" ]; then
+          .config/log warn 'Failed to run `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
+          prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+        fi
 
   python:
     deps:
       - :install:python:requirements
     desc: Automatically format Python files using Black
+    hide: '{{ne .REPOSITORY_TYPE "python"}}'
     summary: |
-      # Automatically format Python files using Black
+      # Automatically Format Python Files with Black
 
       Black is the defacto standard when it comes to autoformatting Python files. This task will
       automatically format files that end with the `.py` extension. It ignores `.py` files that are
@@ -203,9 +325,8 @@ tasks:
           {{.PYTHON_HANDLE}}black {{.CLI_ARGS}}
         {{else}}
           while read PATHH; do
-            {{.PYTHON_HANDLE}}black "$PATHH" &
+            {{.PYTHON_HANDLE}}black "$PATHH"
           done < <(find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.py' \))
-          wait
         {{end}}
 
   shell:
@@ -216,7 +337,7 @@ tasks:
   shellcheck:
     deps:
       - :install:npm:shellcheck
-    desc: (Experimental) Automatically apply fixes to .sh and .sh.j2 files using Shellcheck
+    desc: Automatically apply fixes to `.sh` and `.sh.j2` files using Shellcheck
     summary: |
       # Automatically apply fixes to shell scripts using Shellcheck
 
@@ -252,10 +373,55 @@ tasks:
             -print0 | xargs -0 {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}} -f diff | git apply
         {{end}}
 
+  spelling:markdown:
+    deps:
+      - :install:go:misspell
+    desc: Auto-fix spelling errors in markdown files using `misspell`
+    log:
+      error: Encountered error while attempting to auto-correct spelling mistakes with `misspell`
+      start: Auto-fixing using the `misspell` spell-check engine
+      success: Successfully auto-fixed files using `misspell`
+    cmds:
+      - >
+        {{if .CLI_ARGS}}
+        misspell -w {{.CLI_ARGS}}
+        {{else}}
+        find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.md' \)
+        -print0 | xargs -0 -r -n1 misspell -w
+        {{end}}
+
+  toml:
+    deps:
+      - :install:python:requirements
+    desc: Format `.toml` files by alphabetizing and flattening
+    summary: |
+      # Automatically format `.toml` files
+
+      [toml-sort](https://pypi.org/project/toml-sort/) will automatically alphabetize and flatten
+      `.toml` files.
+
+      **Example running on whole project:**
+      `task fix:toml`
+
+      **Example usage on specific file:**
+      `task fix:toml -- pyproject.toml`
+    log:
+      error: Encountered an error while running `toml-sort`
+      start: Running `toml-sort` auto-fixer
+      success: Successfully ran the `toml-sort` auto-fixer
+    cmds:
+      - |
+        {{if .CLI_ARGS}}
+          {{.PYTHON_HANDLE}}toml-sort -i --all {{.CLI_ARGS}}
+        {{else}}
+          while read PATHH; do
+            {{.PYTHON_HANDLE}}toml-sort -i --all "$PATHH"
+          done < <(find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.toml' \))
+        {{end}}
+
   xml:
     deps:
       - :install:npm:eslint
-    desc: Autofix XML files
     summary: |
       # Autofix XML files
 
@@ -276,9 +442,9 @@ tasks:
         --format pretty --ext .xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
 
   yaml:
-    desc: Autofix YML files
+    desc: Auto-format and sort YML files
     summary: |
-      # Autofix YML files
+      # Auto-Format and Sort YML files
 
       This task will automatically apply updates to YML files. It currently performs the following
       tasks:
@@ -329,9 +495,8 @@ tasks:
           yamlDashes '{{.CLI_ARGS}}'
         {{else}}
           while read YML_FILE; do
-            yamlDashes "$YML_FILE" &
+            yamlDashes "$YML_FILE"
           done < <(find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.yml' -o -name '*.yaml' \))
-          wait
         {{end}}
 
   yaml:order:
diff --git a/.config/taskfiles/lint/Taskfile.yml b/.config/taskfiles/lint/Taskfile.yml
--- a/.config/taskfiles/lint/Taskfile.yml
+++ b/.config/taskfiles/lint/Taskfile.yml
@@ -24,6 +24,7 @@ tasks:
       - :symlink:{{.REPOSITORY_SUBTYPE}}
       - :install:python:requirements
     desc: Lint Ansible projects using Ansible Lint
+    hide: '{{ne .REPOSITORY_TYPE "ansible"}}'
     summary: |
       # Lint an Ansible project using Ansible Lint
 
@@ -41,9 +42,7 @@ tasks:
       start: Linting project with Ansible Lint
       success: Validated project with Ansible Lint
     cmds:
-      - |
-        .config/log info 'Linting the project with ansible-lint'
-        {{.PYTHON_HANDLE}}ansible-lint -c {{.ANSIBLE_LINT_CONFIG}}
+      - '{{.PYTHON_HANDLE}}ansible-lint -c {{.ANSIBLE_LINT_CONFIG}}'
 
   any:
     deps:
@@ -62,12 +61,36 @@ tasks:
   codeclimate:
     deps:
       - :install:software:codeclimate
+      - :lint:codeclimate:load:custom-engines
+    desc: Run CodeClimate with all available linters
+    summary: |
+      # Run CodeClimate
+
+      CodeClimate provides a birds-eye view of all the various possible issues that there may be
+      with a project by leveraging various plugins called CodeClimate engines.
+
+      This task will run all available linters defined in `.codeclimate.yml` after substituting
+      some of the standard linters with custom engines built by Megabyte Labs.
+
+      **Example:**
+      `task lint:codeclimate`
+
+      You can optionally output the results in HTML format. To do so, pass in the name of the output
+      HTML file you would like to generate.
+
+      **Example generating HTML results:**
+      `task lint:codeclimate -- ' -f html > codeclimate.html'`
+
+      You can also specify a specific path for CodeClimate to scan:
+
+      **Example specifying specific path to analyze:**
+      `task lint:codeclimate -- ' ./src/component'
     log:
       error: '`codeclimate` has detected errors'
       start: Running `codeclimate`
       success: Successfully validated the project by running `codeclimate`
     cmds:
-      - codeclimate
+      - CODECLIMATE_DEBUG=1 codeclimate analyze --dev{{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}
 
   commit:
     deps:
@@ -85,7 +108,8 @@ tasks:
       error: Encountered error while linting commit message ({{.CLI_ARGS}})
     cmds:
       - |
-        if [ ! -z '{{.CLI_ARGS}}' ] && [ '{{.CLI_ARGS}}' != '.git/MERGE_MSG' ] && [ "$(head -c12 < .git/MERGE_MSG)" != 'Merge branch' ]; then
+        if [ ! -z '{{.CLI_ARGS}}' ] && [ '{{.CLI_ARGS}}' != '.git/MERGE_MSG' ] \
+        && [ "$(test -f .git/MERGE_MSG && head -c12 < .git/MERGE_MSG)" != 'Merge branch' ]; then
           cp '{{.CLI_ARGS}}' '{{.CLI_ARGS}}.bak'
           TMP="$(mktemp)"
           COMMIT_MSG_NOEMOJI="$(sed 's/^..//' < '{{.CLI_ARGS}}' | xargs)"
@@ -131,15 +155,19 @@ tasks:
       `task lint:docker -- CustomDockerfile`
 
       For more information, see [Hadolint's GitHub page](https://github.com/hadolint/hadolint).
+    vars:
+      PWD:
+        sh: echo "${PWD}/"
+    hide:
+      sh: '[ ! -f Dockerfile ]'
     log:
       error: Hadolint reported errors
       start: Linting {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}the project{{end}} with Hadolint
       success: Hadolint reported no errors
     cmds:
       - |
-        .config/log info 'Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}all Dockerfiles{{end}} with a Hadolint Docker image'
         {{if .CLI_ARGS}}
-          docker run -v "$PWD:/work" -w /work megabytelabs/hadolint:slim {{.CLI_ARGS}}
+          docker run -v "$PWD:/work" -w /work megabytelabs/hadolint:slim {{.CLI_ARGS | replace .PWD ""}}
         {{else}}
           find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name Dockerfile -o \
             -name Dockerfile.j2 \) -print0 | xargs -0 -r -n1 docker run -v "$PWD:/work" -w /work \
@@ -150,11 +178,30 @@ tasks:
     cmds:
       - task: docker
 
+  dockerfilelint:
+    deps:
+      - :install:npm:dockerfilelint
+    desc: Lint a Dockerfile with `dockerfilelint`
+    hide:
+      sh: '[ ! -f Dockerfile ]'
+    log:
+      error: '`dockerfilelint` reported errors'
+      start: Linting {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}the project{{end}} with `dockerfilelint`
+      success: '`dockerfilelint` ran successfully and reported no errors'
+    cmds:
+      - |
+        {{if .CLI_ARGS}}
+          dockerfilelint {{.CLI_ARGS | replace .PWD ""}}
+        {{else}}
+          find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name Dockerfile -o \
+            -name Dockerfile.j2 \) -print0 | xargs -0 -r -n1 dockerfilelint
+        {{end}}
+
   eslint:
     deps:
       - :install:modules:local
       - :install:npm:eslint
-    desc: Lint with `eslint`
+    desc: Lint with ESLint
     summary: |
       # Lint with `eslint`
 
@@ -179,11 +226,27 @@ tasks:
         {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
         --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
+  eslint:staged:
+    deps:
+      - :install:modules:local
+      - :install:npm:eslint
+    desc: Lint only modified files with ESLint
+    env:
+      ESLINT_STAGED_ONLY: on
+    log:
+      error: Failed to lint modified files with ESLint
+      start: Linting modified files with ESLint
+      success: Successfully linted modified files with ESLint
+    cmds:
+      - >
+        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
+        --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+
   eslint:warn-all:
     deps:
       - :install:modules:local
       - :install:npm:eslint
-    desc: Convert ESLint errors into warnings in `package.json`
+    desc: Convert ESLint errors into warnings by saving the modified configuration inside `package.json`
     summary: |
       # Convert ESLint Errors into Warnings
 
@@ -204,11 +267,60 @@ tasks:
         while read LINE; do
           TMP="$(mktemp)";
           ESLINT_RULE="$(echo "$LINE" | grep 'errors ' | sed 's/.*rule:\ //')";
-          if [ -n "$ESLINT_RULE" ]; then
+          if [ -n "$ESLINT_RULE" ] && [ "$ESLINT_RULE" != 'syntax error' ]; then
             jq --arg rule "$ESLINT_RULE" '.eslintConfig.rules[$rule] = "warn"' package.json > "$TMP";
             mv "$TMP" package.json;
           fi;
         done < "$ESLINT_TMP"
+
+  go:
+    desc: Lint Go with all available Go linters
+    summary: |
+      # Lint Go Files
+
+      This task will lint Go files with the following linters:
+
+      * [go]()
+
+      If you would like to skip linting the whole project and instead lint an
+      individual file, then you can do so by passing the file path as a CLI
+      parameter like so:
+
+      **Example linting individual file:**
+      `task lint:go -- path/filename.go`
+    cmds:
+      - task: go:vet
+
+  go:vet:
+    deps:
+      - :install:software:go
+    summary: |
+      # Inspect with Go Vet
+
+      This task inspects the source code with `go vet`.
+
+      If you need to add flags to the command, you can specify them in
+      `blueprint.goVetFlags`. `goVetFlags` can also be set in upstream variable
+      sources but this lint command does not force the generation of the
+      `.variables.json` file. If it cannot read `goVetFlags` in the `.variables.json` file
+      (perhaps because it was not generated yet), it will read `.blueprint.goVetFlags`
+      from `package.json`.
+
+      If you would like to run `go vet` on a specific path then you can pass the path
+      in as a CLI argument.
+
+      **Example of running `go vet` on a specific path:**
+      `task lint:go:vet -- path/to/file.go`
+    vars:
+      GO_VET_FLAGS:
+        sh: |
+          if [ -f .variables.json ]; then
+            echo " $(jq -r '.goVetFlags' .variables.json)"
+          else
+            echo " $(jq -r '.blueprint.goVetFlags' package.json | sed 's/null//')"
+          fi
+    cmds:
+      - go vet{{.GO_VET_FLAGS}}{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}
 
   js:
     deps:
@@ -239,6 +351,7 @@ tasks:
     deps:
       - :install:software:packer
     desc: Validate the Packer templates ending with `template.json`
+    hide: '{{ne .REPOSITORY_TYPE "packer"}}'
     summary: |
       # Validate Packer templates
 
@@ -269,6 +382,24 @@ tasks:
           done
         {{end}}
 
+  php:
+    desc: Lint PHP with all available PHP linters
+    summary: |
+      # Lint PHP Files
+
+      This task will lint PHP files with the following linters:
+
+      * [go]()
+
+      If you would like to skip linting the whole project and instead lint an
+      individual file, then you can do so by passing the file path as a CLI
+      parameter like so:
+
+      **Example linting individual file:**
+      `task lint:php -- path/filename.php`
+    cmds:
+      - task: :donothing
+
   prettier:
     deps:
       - :install:modules:local
@@ -291,13 +422,19 @@ tasks:
       start: Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}the project{{end}} with Prettier
       success: Prettier successfully finished
     cmds:
-      - '{{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - |
+        {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
+        if [ -n "$EXIT_CODE" ]; then
+          .config/log warn 'Failed to lint with `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
+          prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+        fi
 
   python:
     deps:
       - :install:python:requirements
     label: lint:python
     desc: Lint Python files using Flake8
+    hide: '{{ne .REPOSITORY_TYPE "python"}}'
     summary: |
       # Lint Python files using Flake8
 
@@ -327,10 +464,8 @@ tasks:
     cmds:
       - |
         {{if .CLI_ARGS}}
-          .config/log info 'Linting {{.CLI_ARGS}} with flake8'
           {{.PYTHON_HANDLE}}flake8 --config {{.FLAKE8_CONFIG}} {{.CLI_ARGS}}
         {{else}}
-          .config/log info 'Linting the project with flake8'
           {{.PYTHON_HANDLE}}flake8 --config {{.FLAKE8_CONFIG}} .
         {{end}}
 
@@ -412,6 +547,24 @@ tasks:
           fi
         ignore_errors: true
 
+  spelling:markdown:
+    deps:
+      - :install:go:misspell
+    desc: Run `misspell` (a spell-checker) on all markdown files
+    log:
+      error: Encountered errors while running `misspell`
+      start: Running `misspell` spell-check
+      success: Successfully ran `misspell` with no errors reported
+    cmds:
+      - >
+        .config/log info 'If errors are found, you can auto-fix them by running `task fix:spelling:markdown`'
+        {{if .CLI_ARGS}}
+        misspell {{.CLI_ARGS}}
+        {{else}}
+        find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.md' \)
+        -print0 | xargs -0 -r -n1 misspell
+        {{end}}
+
   spelling:staged:
     deps:
       - :install:npm:cspell
@@ -436,7 +589,6 @@ tasks:
   toml:
     deps:
       - :install:python:requirements
-    desc: Lint TOML files
     summary: |
       # Lint TOML files
 
@@ -459,6 +611,8 @@ tasks:
     deps:
       - :install:software:vagrant
     desc: Validate the Vagrantfile
+    hide:
+      sh: '[ ! -f Vagrantfile ]'
     summary: |
       # Validate the Vagrantfile
 
@@ -477,7 +631,6 @@ tasks:
   xml:
     deps:
       - :install:python:requirements
-    desc: Lint XML files
     summary: |
       # Lint XML files
 
@@ -499,7 +652,7 @@ tasks:
   yaml:
     deps:
       - :install:python:requirements
-    desc: Lint .yml files using YAML Lint
+    desc: Lint `.yml` files using YAML Lint
     summary: |
       # Lint YML files using YAML Lint
 
